<template>
    <b-container class="page-container">
        <b-card>
            <b-row>
                <b-col>
                    <h1>Predicted Points</h1>
                    <p class='lead'>Select a down and distance points to begin generating visualizations.</p>
                    <p class='text-muted'>Disclaimer: This model was generated by training an artificial neural network. It was mainly done for fun and is not meant to be taken too seriously.</p>
                </b-col>
            </b-row>
        </b-card>
        <b-row>
            <b-col>
                <b-card>
                    <b-row>
                        <b-col />
                        <b-col lg='3'>
                            <b-row class='justify-content-center'><label>Down</label></b-row>
                            <b-form-select v-model="down" :options='downs' @change="updateDown">
                                <option :value="null">Please select a down</option>
                            </b-form-select>
                        </b-col>
                        <b-col lg='3'>
                            <b-row class='justify-content-center'><label>Distance</label></b-row>
                            <b-form-input type='number' min='1' max='99' v-model="distance" @change="updateDistance">
                            </b-form-input>
                        </b-col>
                        <b-col />
                    </b-row>
                </b-card>
            </b-col>
        </b-row>
        <b-row>
            <b-col>
                <b-card>
                    <matchup-scatter :height='200' :chart-data='scatterData' :options='scatterOptions'></matchup-scatter>
                </b-card>
            </b-col>
        </b-row>
    </b-container>
</template>

<script>
    import MatchupScatter from '@/components/MatchupScatter.vue';

    export default {
        components: {
            MatchupScatter
        },
        data() {
            return {
                down: null,
                distance: null,
                downs: [1, 2, 3, 4],
                scatterData: [],
                scatterOptions: {
                    legend: {
                        display: false
                    },
                    title: {
                        display: true,
                        text: 'Predicted Points'
                    },
                    scales: {
                        yAxes: [{
                            ticks: {
                                min: -2,
                                max: 6
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Predicted Points'
                            }
                        }],
                        xAxes: [{
                            ticks: {
                                min: 0,
                                max: 100
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Yardline'
                            }
                        }]
                    }
                }
            }
        },
        methods: {
            refreshData(year) {
                if (year) {
                    this.year = year;
                    this.$axios.get('/ratings/sp', {
                        params: {
                            year: this.year
                        }
                    }).then(results => {
                        this.results = results.data.filter(r => r.team != 'nationalAverages');
                        this.reloadData();
                    });
                }
            },
            updateDown(down) {
                this.down = down;
                this.reloadData();
            },
            updateDistance(distance) {
                this.distance = distance;
                this.reloadData();
            },
            reloadData() {
                if (this.down && this.distance) {
                    this.$axios.get('/ppa/predicted', {
                        params: {
                            down: this.down,
                            distance: this.distance
                        }
                    }).then(results => {
                        this.scatterData = {
                            datasets: [{
                                pointRadius: 5,
                                fill: true,
                                data: results.data.map(d => ({
                                    x: d.yardLine,
                                    y: d.predictedPoints
                                }))
                            }]
                        };
                    })
                }
            }
        }
    }

</script>

<style lang='scss'>

</style>
